# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.destroy_all
Book.destroy_all
Sale.destroy_all


User.create(name: "Farhan", address: "NYC", email: "farhan@farhan.com", password: "farhan")
User.create(name: "Josh", address: "NYC", email: "josh@josh.com", password: "josh")

Book.create(title: "1984", author: "George Orwell", genre: "Thriller", synopsis: "In 1984, London is a grim city in the totalitarian state of Oceania where Big Brother is always watching you and the Thought Police can practically read your mind. Winston Smith is a man in grave danger for the simple reason that his memory still functions. Drawn into a forbidden love affair, Winston finds the courage to join a secret revolutionary organization called The Brotherhood, dedicated to the destruction of the Party. Together with his beloved Julia, he hazards his life in a deadly match against the powers that be.", img_url: "https://books.google.com/books/content/images/frontcover/kotPYEqx7kMC?fife=w200-h300", price: 9.99)
Book.create(title: "48 Laws Of Power", author: "Robert Greene", genre: "Strategy", synopsis: "Some laws teach the need for prudence ('Law 1: Never Outshine the Master'), others teach the value of confidence ('Law 28: Enter Action with Boldness'), and many recommend absolute self-preservation ('Law 15: Crush Your Enemy Totally'). Every law, though, has one thing in common: an interest in total domination. In a bold and arresting two-color package, The 48 Laws of Power is ideal whether your aim is conquest, self-defense, or simply to understand the rules of the game.", img_url: "https://books.google.com/books/content/images/frontcover/afCxg5sogvAC?fife=w200-h300", price: 18.99)
Book.create(title: "The Savior", author: "J.R. Ward", genre: "Adventure", synopsis: "In the next heart-pounding novel in the #1 New York Times bestselling Black Dagger Brotherhood series, J.R. Ward delivers a brand-new paranormal passion with the story of Murhder, who returns after his appearance in The Thief!", img_url: "https://books.google.com/books/content/images/frontcover/LaRzDwAAQBAJ?fife=w200-h300", price: 5.99)
Book.create(title: "On the Origin of Species: By Means of Natural Selection", genre: "Education", synopsis: "It took Charles Darwin more than twenty years to publish this book, in part because he realized that it would ignite a firestorm of controversy. On the Origin of Species first appeared in 1859, and it remains a continuing source of conflict to this day. Even among those who reject its ideas, however, the work's impact is undeniable. In science, philosophy, and theology, this is a book that changed the world.
In addition to its status as the focus of a dramatic turning point in scientific thought, On the Origin of Species stands as a remarkably readable study. Carefully reasoned and well-documented in its arguments, the work offers coherent views of natural selection, adaptation, the struggle for existence, survival of the fittest, and other concepts that form the foundation of modern evolutionary theory. This volume is a reprint of the critically acclaimed first edition.", author: "Charles Darwin", img_url: "https://books.google.com/books/content/images/frontcover/goWjsFhpGHMC?fife=w200-h300", price: 4.99)
Book.create(title: "Fire & Blood: 300 Years Before A Game of Thrones (A Targaryen History)", author: "George R.R. Martin", genre: "Adventure", synopsis: "With all the scope and grandeur of Gibbon’s The History of the Decline and Fall of the Roman Empire, Fire & Blood is the the first volume of the definitive two-part history of the Targaryens, giving readers a whole new appreciation for the dynamic, often bloody, and always fascinating history of Westeros.", img_url: "https://books.google.com/books/content/images/frontcover/Mj5XDwAAQBAJ?fife=w200-h300", price: 14.99)
Book.create(title: "The Way Of The Shadows", author: "Brent Weeks", genre: "Adventure", synopsis: "For Azoth, survival is precarious. Something you never take for granted. As a guild rat, he's grown up in the slums, and learned to judge people quickly--and to take risks. Risks like apprenticing himself to Durzo Blint.", img_url: "https://books.google.com/books/content/images/frontcover/Zgj5OmP9b8IC?fife=w200-h300", price: 6.99)
Book.create(title: "Assassin's Creed: Renaissance", author: "Oliver Bowden",genre: "Adventure", synopsis: "Betrayed by the ruling families of Italy, Ezio Auditore embarks upon an epic quest for vengeance. To eradicate corruption and restore his family's honor, he will learn the art of the Assassins.Along the way, Ezio will call upon the wisdom of such great minds as Leonardo da Vinci and Niccolo Machiavelli, knowing that survival is bound to the skills by which he must live.To his allies, he will become a force for change in his fight for freedom and justice. To his enemies, he will become a threat dedicated to the destruction of the tyrants abusing the people of Italy. So begins an epic story of power, revenge, and conspiracy.", img_url: "https://books.google.com/books/content/images/frontcover/4qjW_QP-V0sC?fife=w200-h300", price: 9.99)
Book.create(title: "Angels & Demons", author: "Dan Brown", genre: "Thriller", synopsis: "Embarking on a frantic hunt through sealed crypts, dangerous catacombs, deserted cathedrals, and even the most secretive vault on earth, Langdon and Vetra follow a 400-year-old trail of ancient symbols that snakes across Rome toward the long-forgotten Illuminati lair...a clandestine location that contains the only hope for Vatican salvation.", img_url: "https://books.google.com/books/content/images/frontcover/K__fyN2gl9gC?fife=w200-h300", price: 8.99)
Book.create(title: "The Da Vince Code", author: "Dan Brown", genre: "Thriller", synopsis: "While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter.", img_url: "https://books.google.com/books/content/images/frontcover/TB0ZDAAAQBAJ?fife=w200-h300", price: 11.99)
Book.create(title: "The Lost Symbol", author: "Dan Brown", genre: "Thriller", synopsis: "When his mentor Peter Solomon—a long-standing Mason and beloved philanthropist—is kidnapped, Langdon realizes that the only way to save Solomon is to accept the mystical invitation and plunge headlong into a clandestine world of Masonic secrets, hidden history, and one inconceivable truth . . . all under the watchful eye of Dan Brown's most terrifying villain to date. Set within the hidden chambers, tunnels, and temples of Washington, D.C., The Lost Symbol is an intelligent, lightning-paced story with surprises at every turn—one of Brown's most riveting novels.", img_url: "https://books.google.com/books/content/images/frontcover/ucpxOA3LDWcC?fife=w200-h300", price: 9.99)
Book.create(title: "Inferno", author: "Dan Brown", genre: "Thriller", synopsis: "Harvard professor of symbology Robert Langdon awakens in an Italian hospital, disoriented and with no recollection of the past thirty-six hours, including the origin of the macabre object hidden in his belongings. With a relentless female assassin trailing them through Florence, he and his resourceful doctor, Sienna Brooks, are forced to flee. Embarking on a harrowing journey, they must unravel a series of codes, which are the work of a brilliant scientist whose obsession with the end of the world is matched only by his passion for one of the most influential masterpieces ever written, Dante Alighieri's The Inferno.", img_url: "https://books.google.com/books/content/images/frontcover/9nloexmq6QsC?fife=w200-h300", price: 9.99)
Book.create(title: "The Origin", author: "Dan Brown", genre: "Thriller", synopsis: "Navigating the dark corridors of hidden history and extreme re­ligion, Langdon and Vidal must evade an enemy whose all-knowing power seems to emanate from Spain’s Royal Palace. They uncover clues that ultimately bring them face-to-face with Kirsch’s shocking discovery…and the breathtaking truth that has long eluded us.", img_url: "https://books.google.com/books/content/images/frontcover/Pz4YDQAAQBAJ?fife=w200-h300", price: 7.99)
Book.create(title: "33 Strategies Of War", author: "Robert Greene", genre: "Strategy", synopsis: "Abundantly illustrated with examples from history, including the folly and genius of everyone from Napoleon to Margaret Thatcher, Shaka the Zulu to Lord Nelson, Hannibal to Ulysses S. Grant, as well as movie moguls, Samurai swordsmen, and diplomats, each of the thirty-three chapters outlines a strategy that will help you win life’s wars. Learn the offensive strategies that require you to maintain the initiative and negotiate from a position of strength, or the defensive strategies designed to help you respond to dangerous situations and avoid unwinnable wars. The great warriors of battlefields and drawing rooms alike demonstrate prudence, agility, balance, and calm, and a keen understanding that the rational, resourceful, and intuitive always defeat the panicked, the uncreative, and the stupid. An indispensable book, The 33 Strategies of War provides all the psychological ammunition you need to overcome patterns of failure and forever gain the upper hand.", img_url: "https://books.google.com/books/content/images/frontcover/dBldXrykXI8C?fife=w200-h300", price: 11.99)
Book.create(title: "The Laws Of Human Nature", author: "Robert Greene", genre: "Strategy", synopsis: "We are social animals. Our very lives depend on our relationships with people. Knowing why people do what they do is the most important tool we can possess, without which our other talents can only take us so far. Drawing from the ideas and examples of Pericles, Queen Elizabeth I, Martin Luther King Jr, and many others, Greene teaches us how to detach ourselves from our own emotions and master self-control, how to develop the empathy that leads to insight, how to look behind people's masks, and how to resist conformity to develop your singular sense of purpose. Whether at work, in relationships, or in shaping the world around you, The Laws of Human Nature offers brilliant tactics for success, self-improvement, and self-defense.", img_url: "https://books.google.com/books/content/images/frontcover/I_1RDwAAQBAJ?fife=w200-h300", price: 15.99)
Book.create(title: "The Art Of Seduction", author: "Robert Greene", genre: "Strategy", synopsis: "When raised to the level of art, seduction, an indirect and subtle form of power, has toppled empires, won elections and enslaved great minds. Immerse yourself in the twenty-four maneuvers and strategies of the seductive process, the ritual by which a seducer gains mastery over his target. Understand how to 'Poeticize Your Presence,' 'Keep them in Suspense – What Comes Next' and 'Master the Art of the Bold Move'. Every bit as essential as The 48 Laws of Power, The Art of Seduction is an indispensable primer of persuasion that reveals one of history's greatest weapons and the ultimate form of power.", img_url: "https://books.google.com/books/content/images/frontcover/gAK4J4d3MNEC?fife=w200-h300", price: 11.99)
Book.create(title: "Mastery", author: "Robert Greene", genre: "Strategy", synopsis: "The bestseller author of The 48 Laws of Power, The Art of Seduction, and The 33 Strategies of War, Robert Greene has spent a lifetime studying the laws of power. Now, he shares the secret path to greatness. With this seminal text as a guide, readers will learn how to unlock the passion within and become masters.", img_url: "https://books.google.com/books/content/images/frontcover/LxZiUSuVIgcC?fife=w200-h300", price: 14.99)
Book.create(title: "Behold A Pale White Horse", author: "William Cooper", genre: "Strategy", synopsis: "Bill Cooper, former United States Naval Intelligence Briefing Team member, reveals information that remains hidden from the public eye. This information has been kept in Top Secret government files since the 1940s. His audiences hear the truth unfold as he writes about the assassination of John F. Kennedy, the war on drugs, the Secret Government and UFOs. ", img_url: "https://books.google.com/books/content/images/frontcover/g0aen3LDErAC?fife=w200-h300", price: 14.99)
Book.create(title: "The Republic", author: "Plato", genre: "Philosophy", synopsis: "Written in the form of a Socratic dialogue, The Republic is an investigation into the nature of an ideal society. In this far-reaching and profoundly influential treatise, Plato explores the concept of justice, the connection between politics and psychology, the difference between words and what they represent, and the roles of art and education, among many other topics. A towering achievement of philosophical insight, The Republic is as relevant to readers today as it was to the citizens of ancient Athens.", img_url: "https://books.google.com/books/content/images/frontcover/POumBAAAQBAJ?fife=w200-h300", price: 2.99)
Book.create(title: "Odyssey", author: "Homer", genre: "Epic Poetry", synopsis: "The epic tale of Odysseus and his ten-year journey home after the Trojan War forms one of the earliest and greatest works of Western literature. Confronted by natural and supernatural threats - shipwrecks, battles, monsters and the implacable enmityof the sea-god Poseidon - Odysseus must test his bravery and native cunning to the full if he is to reach his homeland safely and overcome the obstacles that, even there, await him.", img_url: "https://books.google.com/books/content/images/frontcover/U2Jovv1NuMsC?fife=w200-h300", price: 9.99)
Book.create(title: "Iliad", author: "Homer", genre: "Epic Poetry", synopsis: "One of the foremost achievements in Western literature, Homer's Iliad tells the story of the darkest episode in the Trojan War. At its centre is Achilles, the greatest warrior-champion of the Greeks, and his refusal to fight after being humiliated by his leader Agamemnon. But when the Trojan Hector kills Achilles' close friend Patroclus, he storms back into battle to take revenge - although knowing this will ensure his own early death. Interwoven with this tragic sequence of events are powerfully moving descriptions of the ebb and flow of battle, of the domestic world inside Troy's besieged city of Ilium, and of the conflicts between the Gods on Olympus as they argue over the fate of mortals.", img_url: "https://books.google.com/books/content/images/frontcover/6xZylvO-wGUC?fife=w200-h300", price: 9.99)
Book.create(title: "The Divine Comedy", author: "Dante Alighieri", genre: "Epic Poetry", synopsis: "Belonging in the immortal company of the great works of literature, Dante Alighieri’s poetic masterpiece, The Divine Comedy, is a moving human drama, an unforgettable visionary journey through the infinite torment of Hell, up the arduous slopes of Purgatory, and on to the glorious realm of Paradise—the sphere of universal harmony and eternal salvation.", img_url: "https://books.google.com/books/content/images/frontcover/p_5l2FCfvF8C?fife=w200-h300", price: 9.99)
Book.create(title: "Complete Stories And Poems Of Edgar Allan Poe", author: "Edgar Allan Poe", genre: "Poetry", synopsis: "This single volume brings together all of Poe's stories and poems, and illuminates the diverse and multifaceted genius of one of the greatest and most influential figures in American literary history.", img_url: "https://books.google.com/books/content/images/frontcover/dgEvp7vQ0f4C?fife=w200-h300", price: 14.99)
Book.create(title: "The Fellowship Of The Rings", author: "J.R.R. Tolkien", genre: "Adventure", synopsis: "In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.", img_url: "https://books.google.com/books/content/images/frontcover/aWZzLPhY4o0C?fife=w200-h300", price: 9.99)
Book.create(title: "The Two Towers", author: "J.R.R. Tolkien", genre: "Adventure", synopsis: "Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.", img_url: "https://books.google.com/books/content/images/frontcover/12e8PJ2T7sQC?fife=w200-h300", price: 9.99)
Book.create(title: "The Return Of The King", author: "J.R.R. Tolkien", genre: "Adventure", synopsis: "As the Shadow of Mordor grows across the land, the Companions of the Ring have become involved in separate adventures. Aragorn, revealed as the hidden heir of the ancient Kings of the West, has joined with the Riders of Rohan against the forces of Isengard, and takes part in the desperate victory of the Hornburg. Merry and Pippin, captured by Orcs, escape into Fangorn Forest and there encounter the Ents. Gandalf has miraculously returned and defeated the evil wizard, Saruman. Sam has left his master for dead after a battle with the giant spider, Shelob; but Frodo is still alive—now in the foul hands of the Orcs. And all the while the armies of the Dark Lord are massing as the One Ring draws ever nearer to the Cracks of Doom.", img_url: "https://books.google.com/books/content/images/frontcover/WZ0f_yUgc0UC?fife=w200-h300", price: 9.99)
Book.create(title: "The Hobbit", author: "J.R.R. Tolkien", genre: "Adventure", synopsis: "A great modern classic and the prelude to The Lord of the Rings. Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure. They have launched a plot to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon. Bilbo reluctantly joins their quest, unaware that on his journey to the Lonely Mountain he will encounter both a magic ring and a frightening creature known as Gollum.", img_url: "https://books.google.com/books/content/images/frontcover/pD6arNyKyi8C?fife=w200-h300", price: 9.99)
Book.create(title: "The Subtle Art Of Not Giving A F*ck: A Counterintuitive Approach To Living A Good Life", author: "Mark Manson", genre: "Self-Help", synopsis: "In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be 'positive' all the time so that we can truly become better, happier people.For decades, we’ve been told that positive thinking is the key to a happy, rich life. 'F**k positivity,' Mark Manson says. 'Let’s be honest, shit is f**ked and we have to live with it.' In his wildly popular Internet blog, Manson doesn’t sugarcoat or equivocate. He tells it like it is—a dose of raw, refreshing, honest truth that is sorely lacking today. The Subtle Art of Not Giving a F**k is his antidote to the coddling, let’s-all-feel-good mindset that has infected American society and spoiled a generation, rewarding them with gold medals just for showing up.", img_url: "https://books.google.com/books/content/images/frontcover/yng_CwAAQBAJ?fife=w200-h300", price: 12.99)
Book.create(title: "Pet Sematary", author: "Stephen King", genre: "Horror", synopsis: "When Dr. Louis Creed takes a new job and moves his family to the idyllic rural town of Ludlow, Maine, this new beginning seems too good to be true. Despite Ludlow’s tranquility, an undercurrent of danger exists here. Those trucks on the road outside the Creed’s beautiful old home travel by just a little too quickly, for one thing…as is evidenced by the makeshift graveyard in the nearby woods where generations of children have buried their beloved pets. Then there are the warnings to Louis both real and from the depths of his nightmares that he should not venture beyond the borders of this little graveyard where another burial ground lures with seductive promises and ungodly temptations. A blood-chilling truth is hidden there—one more terrifying than death itself, and hideously more powerful. As Louis is about to discover for himself sometimes, dead is better…", img_url: "https://books.google.com/books/content/images/frontcover/iEWAAwAAQBAJ?fife=w200-h300", price: 13.99)
Book.create(title: "It", author: "Stephen King", genre: "Horror", synopsis: "They were seven teenagers when they first stumbled upon the horror. Now they are grown-up men and women who have gone out into the big world to gain success and happiness. But the promise they made twenty-eight years ago calls them reunite in the same place where, as teenagers, they battled an evil creature that preyed on the city’s children. Now, children are being murdered again and their repressed memories of that terrifying summer return as they prepare to once again battle the monster lurking in Derry’s sewers.", img_url: "https://books.google.com/books/content/images/frontcover/-rUACwAAQBAJ?fife=w200-h300", price: 12.99)
Book.create(title: "The Shining", author: "Stephen King", genre: "Horror", synopsis: "Terrible events occur at an isolated hotel in the off season, when a small boy with psychic powers struggles to hold his own against the forces of evil that are driving his father insane.", img_url: "https://books.google.com/books/content/images/frontcover/8VnJLu3AvvQC?fife=w200-h300", price: 8.99)
Book.create(title: "Carrie", author: "Stephen King", genre: "Horror", synopsis: "Carrie White may be picked on by her classmates, but she has a gift. She can move things with her mind. Doors lock. Candles fall. This is her power and her problem. Then, an act of kindness, as spontaneous as the vicious taunts of her classmates, offers Carrie a chance to be a normal...until an unexpected cruelty turns her gift into a weapon of horror and destruction that no one will ever forget.", img_url: "https://books.google.com/books/content/images/frontcover/FNxGvn1SCVMC?fife=w200-h300", price: 7.99)
Book.create(title: "The Firm: A Novel", author: "John Grisham", genre: "Fiction", synopsis: "When Mitch McDeere signed on with Bendini, Lambert & Locke of Memphis, he thought that he and his beautiful wife, Abby, were on their way. The firm leased him a BMW, paid off his school loans, arranged a mortgage, and hired the McDeeres a decorator. Mitch should have remembered what his brother Ray–doing fifteen years in a Tennessee jail–already knew: You never get nothing for nothing. Now the FBI has the lowdown on Mitch’s firm and needs his help. Mitch is caught between a rock and a hard place, with no choice–if he wants to live.", img_url: "https://books.google.com/books/content/images/frontcover/y1bJQrOBceEC?fife=w200-h300", price: 9.99)
Book.create(title: "The Innocent Man: Murder And Injustice In A Small Town", author: "John Grisham", genre: "Fiction", synopsis: "In the town of Ada, Oklahoma, Ron Williamson was going to be the next Mickey Mantle. But on his way to the Big Leagues, Ron stumbled, his dreams broken by drinking, drugs, and women. Then, on a winter night in 1982, not far from Ron’s home, a young cocktail waitress named Debra Sue Carter was savagely murdered. The investigation led nowhere. Until, on the flimsiest evidence, it led to Ron Williamson. The washed-up small-town hero was charged, tried, and sentenced to death—in a trial littered with lying witnesses and tainted evidence that would shatter a man’s already broken life, and let a true killer go free.", img_url: "https://books.google.com/books/content/images/frontcover/vtENwqjzRxMC?fife=w200-h300", price: 9.99)
Book.create(title: "Chariots Of The Gods", author: "Erich Von Daniken", genre: "Pseudohistory", synopsis: "Immediately recognized as a work of monumental importance, Chariots of the Godsendures as proof that Earth has been visited repeatedly by advanced aliens from other worlds. Here, Erich von Däniken examines ancient ruins, lost cities, spaceports, and a myriad of hard scientific facts that point to extraterrestrial intervention in human history. Most incredible of all, however, is von Däniken's theory that we are the descendants of these galactic pioneers—and he reveals the archaeological discoveries that prove it...
", img_url: "https://books.google.com/books/content/images/frontcover/TRMepagkRcYC?fife=w200-h300", price: 8.99)
Book.create(title: "The Gods Never Left Us", author: "Erich Von Daniken", genre: "Pseudohistory", synopsis: "The Gods Never Left Us contends that recent advancements in biotechnology, astrophysics, engineering, and artificial intelligence not only give us a fresh perspective on his ancient astronaut theory but actually validates it. We are—as a race—embarking on the exact same trajectory of our own interplanetary colonization, just as von Däniken suggested Earth itself was colonized.", img_url: "https://books.google.com/books/content/images/frontcover/kS1xDwAAQBAJ?fife=w200-h300", price: 10.99)
Book.create(title: "Steve Jobs", author: "Walter Isaacson", genre: "Biography", synopsis: "Based on more than forty interviews with Jobs conducted over two years—as well as interviews with more than a hundred family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing.", img_url: "https://books.google.com/books/content/images/frontcover/I6R8MXStPXgC?fife=w200-h300", price: 14.99)
Book.create(title: "Becoming", author: "Michelle Obama", genre: "Memoir", synopsis: "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her—from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work, to her time spent at the world’s most famous address. With unerring honesty and lively wit, she describes her triumphs and her disappointments, both public and private, telling her full story as she has lived it—in her own words and on her own terms. Warm, wise, and revelatory, Becoming is the deeply personal reckoning of a woman of soul and substance who has steadily defied expectations—and whose story inspires us to do the same.", img_url: "https://books.google.com/books/content/images/frontcover/YbtNDwAAQBAJ?fife=w200-h300", price: 14.99)
Book.create(title: "The Complete Poetry", author: "Maya Angelou", genre: "Poetry", synopsis: "Throughout her illustrious career in letters, Maya Angelou gifted, healed, and inspired the world with her words. Now the beauty and spirit of those words live on in this new and complete collection of poetry that reflects and honors the writer’s remarkable life.", img_url: "https://books.google.com/books/content/images/frontcover/_ph5BAAAQBAJ?fife=w200-h300", price: 12.99)
