# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.destroy_all
Book.destroy_all
Sale.destroy_all


User.create(name: "Farhan", address: "NYC", email: "farhan@farhan.com", password: "farhan")
User.create(name: "Josh", address: "NYC", email: "josh@josh.com", password: "josh")

Book.create(title: "1984", author: "George Orwell", genre: "Thriller", synopsis: "In 1984, London is a grim city in the totalitarian state of Oceania where Big Brother is always watching you and the Thought Police can practically read your mind. Winston Smith is a man in grave danger for the simple reason that his memory still functions. Drawn into a forbidden love affair, Winston finds the courage to join a secret revolutionary organization called The Brotherhood, dedicated to the destruction of the Party. Together with his beloved Julia, he hazards his life in a deadly match against the powers that be.", img_url: "https://books.google.com/books/content/images/frontcover/kotPYEqx7kMC?fife=w200-h300", price: 9.99)
Book.create(title: "48 Laws Of Power", author: "Robert Greene", genre: "Strategy", synopsis: "Some laws teach the need for prudence ('Law 1: Never Outshine the Master'), others teach the value of confidence ('Law 28: Enter Action with Boldness'), and many recommend absolute self-preservation ('Law 15: Crush Your Enemy Totally'). Every law, though, has one thing in common: an interest in total domination. In a bold and arresting two-color package, The 48 Laws of Power is ideal whether your aim is conquest, self-defense, or simply to understand the rules of the game.", img_url: "https://books.google.com/books/content/images/frontcover/afCxg5sogvAC?fife=w200-h300", price: 18.99)
Book.create(title: "The Savior", author: "J.R. Ward", genre: "Adventure", synopsis: "In the next heart-pounding novel in the #1 New York Times bestselling Black Dagger Brotherhood series, J.R. Ward delivers a brand-new paranormal passion with the story of Murhder, who returns after his appearance in The Thief!", img_url: "https://books.google.com/books/content/images/frontcover/LaRzDwAAQBAJ?fife=w200-h300", price: 5.99)
Book.create(title: "On the Origin of Species: By Means of Natural Selection", genre: "Education", synopsis: "It took Charles Darwin more than twenty years to publish this book, in part because he realized that it would ignite a firestorm of controversy. On the Origin of Species first appeared in 1859, and it remains a continuing source of conflict to this day. Even among those who reject its ideas, however, the work's impact is undeniable. In science, philosophy, and theology, this is a book that changed the world.
In addition to its status as the focus of a dramatic turning point in scientific thought, On the Origin of Species stands as a remarkably readable study. Carefully reasoned and well-documented in its arguments, the work offers coherent views of natural selection, adaptation, the struggle for existence, survival of the fittest, and other concepts that form the foundation of modern evolutionary theory. This volume is a reprint of the critically acclaimed first edition.", author: "Charles Darwin", img_url: "https://books.google.com/books/content/images/frontcover/goWjsFhpGHMC?fife=w200-h300", price: 4.99)
Book.create(title: "Fire & Blood: 300 Years Before A Game of Thrones (A Targaryen History)", author: "George R.R. Martin", genre: "Adventure", synopsis: "With all the scope and grandeur of Gibbon’s The History of the Decline and Fall of the Roman Empire, Fire & Blood is the the first volume of the definitive two-part history of the Targaryens, giving readers a whole new appreciation for the dynamic, often bloody, and always fascinating history of Westeros.", img_url: "https://books.google.com/books/content/images/frontcover/Mj5XDwAAQBAJ?fife=w200-h300", price: 14.99)
Book.create(title: "The Way Of The Shadows", author: "Brent Weeks", img_url: "https://books.google.com/books/content/images/frontcover/Zgj5OmP9b8IC?fife=w200-h300", price: 6.99)
Book.create(title: "Assassin's Creed: Renaissance", author: "Oliver Bowden", img_url: "https://books.google.com/books/content/images/frontcover/4qjW_QP-V0sC?fife=w200-h300", price: 9.99)
Book.create(title: "Angels & Demons", author: "Dan Brown", genre: "Thriller", synopsis: "Embarking on a frantic hunt through sealed crypts, dangerous catacombs, deserted cathedrals, and even the most secretive vault on earth, Langdon and Vetra follow a 400-year-old trail of ancient symbols that snakes across Rome toward the long-forgotten Illuminati lair...a clandestine location that contains the only hope for Vatican salvation.", img_url: "https://books.google.com/books/content/images/frontcover/K__fyN2gl9gC?fife=w200-h300", price: 8.99)
Book.create(title: "The Da Vince Code", author: "Dan Brown", genre: "Thriller", synopsis: "While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter.", img_url: "https://books.google.com/books/content/images/frontcover/TB0ZDAAAQBAJ?fife=w200-h300", price: 11.99)
Book.create(title: "The Lost Symbol", author: "Dan Brown", genre: "Thriller", synopsis: "When his mentor Peter Solomon—a long-standing Mason and beloved philanthropist—is kidnapped, Langdon realizes that the only way to save Solomon is to accept the mystical invitation and plunge headlong into a clandestine world of Masonic secrets, hidden history, and one inconceivable truth . . . all under the watchful eye of Dan Brown's most terrifying villain to date. Set within the hidden chambers, tunnels, and temples of Washington, D.C., The Lost Symbol is an intelligent, lightning-paced story with surprises at every turn—one of Brown's most riveting novels.", img_url: "https://books.google.com/books/content/images/frontcover/ucpxOA3LDWcC?fife=w200-h300", price: 9.99)
Book.create(title: "Inferno", author: "Dan Brown", genre: "Thriller", synopsis: "Harvard professor of symbology Robert Langdon awakens in an Italian hospital, disoriented and with no recollection of the past thirty-six hours, including the origin of the macabre object hidden in his belongings. With a relentless female assassin trailing them through Florence, he and his resourceful doctor, Sienna Brooks, are forced to flee. Embarking on a harrowing journey, they must unravel a series of codes, which are the work of a brilliant scientist whose obsession with the end of the world is matched only by his passion for one of the most influential masterpieces ever written, Dante Alighieri's The Inferno.", img_url: "https://books.google.com/books/content/images/frontcover/9nloexmq6QsC?fife=w200-h300", price: 9.99)
Book.create(title: "The Origin", author: "Dan Brown", genre: "Thriller", synopsis: "Navigating the dark corridors of hidden history and extreme re­ligion, Langdon and Vidal must evade an enemy whose all-knowing power seems to emanate from Spain’s Royal Palace. They uncover clues that ultimately bring them face-to-face with Kirsch’s shocking discovery…and the breathtaking truth that has long eluded us.", img_url: "https://books.google.com/books/content/images/frontcover/Pz4YDQAAQBAJ?fife=w200-h300", price: 7.99)
Book.create(title: "33 Strategies Of War", author: "Robert Greene", genre: "Strategy", synopsis: "Abundantly illustrated with examples from history, including the folly and genius of everyone from Napoleon to Margaret Thatcher, Shaka the Zulu to Lord Nelson, Hannibal to Ulysses S. Grant, as well as movie moguls, Samurai swordsmen, and diplomats, each of the thirty-three chapters outlines a strategy that will help you win life’s wars. Learn the offensive strategies that require you to maintain the initiative and negotiate from a position of strength, or the defensive strategies designed to help you respond to dangerous situations and avoid unwinnable wars. The great warriors of battlefields and drawing rooms alike demonstrate prudence, agility, balance, and calm, and a keen understanding that the rational, resourceful, and intuitive always defeat the panicked, the uncreative, and the stupid. An indispensable book, The 33 Strategies of War provides all the psychological ammunition you need to overcome patterns of failure and forever gain the upper hand.", img_url: "https://books.google.com/books/content/images/frontcover/dBldXrykXI8C?fife=w200-h300", price: 11.99)
Book.create(title: "The Laws Of Human Nature", author: "Robert Greene", genre: "Strategy", synopsis: "We are social animals. Our very lives depend on our relationships with people. Knowing why people do what they do is the most important tool we can possess, without which our other talents can only take us so far. Drawing from the ideas and examples of Pericles, Queen Elizabeth I, Martin Luther King Jr, and many others, Greene teaches us how to detach ourselves from our own emotions and master self-control, how to develop the empathy that leads to insight, how to look behind people's masks, and how to resist conformity to develop your singular sense of purpose. Whether at work, in relationships, or in shaping the world around you, The Laws of Human Nature offers brilliant tactics for success, self-improvement, and self-defense.", img_url: "https://books.google.com/books/content/images/frontcover/I_1RDwAAQBAJ?fife=w200-h300", price: 15.99)
Book.create(title: "The Art Of Seduction", author: "Robert Greene", genre: "Strategy", synopsis: "When raised to the level of art, seduction, an indirect and subtle form of power, has toppled empires, won elections and enslaved great minds. Immerse yourself in the twenty-four maneuvers and strategies of the seductive process, the ritual by which a seducer gains mastery over his target. Understand how to 'Poeticize Your Presence,' 'Keep them in Suspense – What Comes Next' and 'Master the Art of the Bold Move'. Every bit as essential as The 48 Laws of Power, The Art of Seduction is an indispensable primer of persuasion that reveals one of history's greatest weapons and the ultimate form of power.", img_url: "https://books.google.com/books/content/images/frontcover/gAK4J4d3MNEC?fife=w200-h300", price: 11.99)
Book.create(title: "Mastery", author: "Robert Greene", genre: "Strategy", synopsis: "The bestseller author of The 48 Laws of Power, The Art of Seduction, and The 33 Strategies of War, Robert Greene has spent a lifetime studying the laws of power. Now, he shares the secret path to greatness. With this seminal text as a guide, readers will learn how to unlock the passion within and become masters.", img_url: "https://books.google.com/books/content/images/frontcover/LxZiUSuVIgcC?fife=w200-h300", price: 14.99)
Book.create(title: "Behold A Pale White Horse", author: "William Cooper", genre: "Strategy", synopsis: "Bill Cooper, former United States Naval Intelligence Briefing Team member, reveals information that remains hidden from the public eye. This information has been kept in Top Secret government files since the 1940s. His audiences hear the truth unfold as he writes about the assassination of John F. Kennedy, the war on drugs, the Secret Government and UFOs. ", img_url: "https://books.google.com/books/content/images/frontcover/g0aen3LDErAC?fife=w200-h300", price: 14.99)
